name = ""

gas_price = '2.5aconst'
gas_adjustment = 1.3
account_prefix = 'archway'
derivation_path = '''m/44'/118'/0'/0/0'''

[networks.testnet]
chain_id = 'osmo-test-4'
network_variant = 'Shared'
grpc_endpoint = 'https://grpc-test.osmosis.zone:443'
rpc_endpoint = 'https://rpc-test.osmosis.zone'

[networks.archway]
chain_id = 'constantine-3'
network_variant = 'Shared'
grpc_endpoint = 'https://grpc.constantine.archway.io'
rpc_endpoint = 'https://rpc.constantine.archway.io'

[accounts.signer]
mnemonic = ''